/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB-A--PC30
 */
public class Editor_de_Texto extends javax.swing.JFrame {

    /**
     * Creates new form Editor_de_Texto
     */
    public Editor_de_Texto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtaEditor = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmItemSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmItemCortar = new javax.swing.JMenuItem();
        jmItemCopiar = new javax.swing.JMenuItem();
        jmItemPegar = new javax.swing.JMenuItem();
        jmnuFuente = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jmItemCourierNew = new javax.swing.JMenuItem();
        jmItemArial = new javax.swing.JMenuItem();
        jmItemFPredeterminada = new javax.swing.JMenuItem();
        jmnuTam = new javax.swing.JMenu();
        jmItem16 = new javax.swing.JMenuItem();
        jmItem24 = new javax.swing.JMenuItem();
        jmItemTPredeterminado = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ivettee/tijeras.png"))); // NOI18N
        jButton1.setToolTipText("Cortar");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ivettee/copiar.png"))); // NOI18N
        jButton2.setToolTipText("Copiar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ivettee/pegar.png"))); // NOI18N
        jButton3.setToolTipText("Pegar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jtxtaEditor.setColumns(20);
        jtxtaEditor.setRows(5);
        jtxtaEditor.setText("HOLAA MUNDOO\n\nTqm Ivette\n");
        jScrollPane1.setViewportView(jtxtaEditor);

        jMenu1.setText("Archivo");

        jmItemSalir.setMnemonic('S');
        jmItemSalir.setText("Salir");
        jMenu1.add(jmItemSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ediciones");

        jmItemCortar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCortar.setMnemonic('T');
        jmItemCortar.setText("Cortar");
        jmItemCortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCortarActionPerformed(evt);
            }
        });
        jMenu2.add(jmItemCortar);

        jmItemCopiar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemCopiar.setMnemonic('C');
        jmItemCopiar.setText("Copiar");
        jMenu2.add(jmItemCopiar);

        jmItemPegar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jmItemPegar.setMnemonic('P');
        jmItemPegar.setText("Pegar");
        jMenu2.add(jmItemPegar);

        jMenuBar1.add(jMenu2);

        jmnuFuente.setMnemonic('F');
        jmnuFuente.setText("Opciones");

        jMenu4.setText("Fuente");

        jmItemCourierNew.setText("Courier New");
        jMenu4.add(jmItemCourierNew);

        jmItemArial.setText("Arial");
        jMenu4.add(jmItemArial);

        jmItemFPredeterminada.setText("Por omisión");
        jMenu4.add(jmItemFPredeterminada);

        jmnuFuente.add(jMenu4);

        jmnuTam.setMnemonic('T');
        jmnuTam.setText("Tamaño");

        jmItem16.setText("16");
        jmnuTam.add(jmItem16);

        jmItem24.setText("24");
        jmnuTam.add(jmItem24);

        jmItemTPredeterminado.setText("Por omisión");
        jmItemTPredeterminado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemTPredeterminadoActionPerformed(evt);
            }
        });
        jmnuTam.add(jmItemTPredeterminado);

        jmnuFuente.add(jmnuTam);

        jMenuBar1.add(jmnuFuente);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemCortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCortarActionPerformed
        // TODO add your handling code here:
        jtxtaEditor.cut();
    }//GEN-LAST:event_jmItemCortarActionPerformed

    private void jmItemTPredeterminadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemTPredeterminadoActionPerformed
        // TODO add your handling code here:
        java.awt.Font f=jtxtaEditor.getFont();
        f=new java.awt.Font(f.getFamily(), f.getStyle(), jmItemTPredeterminado.getSize());
        jtxtaEditor.setFont(f);
        }
    }//GEN-LAST:event_jmItemTPredeterminadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor_de_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor_de_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor_de_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor_de_Texto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor_de_Texto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmItem16;
    private javax.swing.JMenuItem jmItem24;
    private javax.swing.JMenuItem jmItemArial;
    private javax.swing.JMenuItem jmItemCopiar;
    private javax.swing.JMenuItem jmItemCortar;
    private javax.swing.JMenuItem jmItemCourierNew;
    private javax.swing.JMenuItem jmItemFPredeterminada;
    private javax.swing.JMenuItem jmItemPegar;
    private javax.swing.JMenuItem jmItemSalir;
    private javax.swing.JMenuItem jmItemTPredeterminado;
    private javax.swing.JMenu jmnuFuente;
    private javax.swing.JMenu jmnuTam;
    private javax.swing.JTextArea jtxtaEditor;
    // End of variables declaration//GEN-END:variables
}
